#include "core/CodeGenerator.h"
#include "core/Project.h"
#include <QFile>
#include <QTemporaryDir>
#include <gtest/gtest.h>

class CodeGenFixture : public ::testing::Test {
protected:
  Project project;

  void SetUp() override { project.setLanguage("C++"); }
};

// ── Empty Graph ─────────────────────────────────────────────────────────────

TEST_F(CodeGenFixture, EmptyGraphProducesComment) {
  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("Pipeline empty"));
}

TEST_F(CodeGenFixture, EmptyGraphNoErrorNodes) {
  auto result = CodeGenerator::generateWithErrors(&project);
  EXPECT_TRUE(result.errorNodes.isEmpty());
  EXPECT_TRUE(result.errors.isEmpty());
}

// ── Start Node as entry point ───────────────────────────────────────────────

TEST_F(CodeGenFixture, StartNodeGeneratesCode) {
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("int main() {\n{Exec}\n  return 0;\n}\n");

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("int main()"));
  EXPECT_TRUE(code.contains("return 0;"));
}

TEST_F(CodeGenFixture, NonStartNodeWithExecOutIsEntryPoint) {
  // A node with exec outputs but no incoming exec links is treated as entry
  Node *n = project.graph()->addNode("Custom.Entry", "Entry", QPointF(0, 0));
  n->addOutput("Exec", "Exec");
  n->setCodeTemplate("// entry\n{Exec}");

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("// entry"));
}

TEST_F(CodeGenFixture, GeneratedByHeader) {
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("Generated by NodeCode Studio"));
}

// ── Exec Flow Sequential Code ───────────────────────────────────────────────

TEST_F(CodeGenFixture, ExecFlowSequentialCode) {
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  Node *print = project.graph()->addNode("IO.Print", "Print", QPointF(100, 0));
  print->addInput("ExecIn", "Exec");
  print->addOutput("ExecOut", "Exec");
  print->addInput("Text", "String", "hello");
  print->setCodeTemplate("std::cout << {Text};\n{ExecOut}");

  project.graph()->addLink(start->id(), start->outputs()[0].id, print->id(),
                           print->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("std::cout"));
  EXPECT_TRUE(code.contains("\"hello\""));
}

TEST_F(CodeGenFixture, ExecFlowChainedNodes) {
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  Node *p1 = project.graph()->addNode("IO.Print", "Print1", QPointF(100, 0));
  p1->addInput("ExecIn", "Exec");
  p1->addOutput("ExecOut", "Exec");
  p1->addInput("Text", "String", "first");
  p1->setCodeTemplate("print({Text});\n{ExecOut}");

  Node *p2 = project.graph()->addNode("IO.Print2", "Print2", QPointF(200, 0));
  p2->addInput("ExecIn", "Exec");
  p2->addOutput("ExecOut", "Exec");
  p2->addInput("Text", "String", "second");
  p2->setCodeTemplate("print({Text});\n{ExecOut}");

  project.graph()->addLink(start->id(), start->outputs()[0].id, p1->id(),
                           p1->inputs()[0].id);
  project.graph()->addLink(p1->id(), p1->outputs()[0].id, p2->id(),
                           p2->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("\"first\""));
  EXPECT_TRUE(code.contains("\"second\""));
}

// ── Inline Value Handling ───────────────────────────────────────────────────

TEST_F(CodeGenFixture, StringInlineValueIsQuoted) {
  // Use exec flow so the node gets processed
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  Node *print = project.graph()->addNode("IO.Print", "Print", QPointF(100, 0));
  print->addInput("ExecIn", "Exec");
  print->addInput("Text", "String", "hello");
  print->setCodeTemplate("print({Text});\n");

  project.graph()->addLink(start->id(), start->outputs()[0].id, print->id(),
                           print->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("\"hello\""));
}

TEST_F(CodeGenFixture, NumberInlineValueNotQuoted) {
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  Node *math = project.graph()->addNode("IO.Calc", "Calc", QPointF(100, 0));
  math->addInput("ExecIn", "Exec");
  math->addInput("A", "Number", "42");
  math->addInput("B", "Number", "7");
  math->addOutput("Result", "Number");
  math->setCodeTemplate("int {Result} = {A} + {B};\n");

  project.graph()->addLink(start->id(), start->outputs()[0].id, math->id(),
                           math->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("42"));
  EXPECT_TRUE(code.contains("7"));
  EXPECT_FALSE(code.contains("\"42\""));
  EXPECT_FALSE(code.contains("\"7\""));
}

TEST_F(CodeGenFixture, BooleanInlineValueNotQuoted) {
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  Node *logic = project.graph()->addNode("Logic.Not", "Not", QPointF(100, 0));
  logic->addInput("ExecIn", "Exec");
  logic->addInput("Value", "Boolean", "true");
  logic->addOutput("Result", "Boolean");
  logic->setCodeTemplate("bool {Result} = !{Value};\n");

  project.graph()->addLink(start->id(), start->outputs()[0].id, logic->id(),
                           logic->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("true"));
  EXPECT_FALSE(code.contains("\"true\""));
}

// ── Linked Data Nodes ───────────────────────────────────────────────────────

TEST_F(CodeGenFixture, LinkedNodesUseVariableNames) {
  // Start -> PrintNode, with a MathNode feeding its data input
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  Node *math = project.graph()->addNode("Math.Add", "Add", QPointF(100, 0));
  math->addInput("ExecIn", "Exec");
  math->addInput("A", "Number", "5");
  math->addInput("B", "Number", "3");
  math->addOutput("Result", "Number");
  math->setCodeTemplate("int {Result} = {A} + {B};\n");

  project.graph()->addLink(start->id(), start->outputs()[0].id, math->id(),
                           math->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  // Output variable should use the node prefix + "Result"
  EXPECT_TRUE(code.contains("Result"));
  EXPECT_TRUE(code.contains("5"));
  EXPECT_TRUE(code.contains("3"));
}

TEST_F(CodeGenFixture, DataLinkSubstitutesSourceVariable) {
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  // Math node produces Result
  Node *math = project.graph()->addNode("Math.Add", "Add", QPointF(100, 0));
  math->addInput("ExecIn", "Exec");
  math->addOutput("ExecOut", "Exec");
  math->addInput("A", "Number", "5");
  math->addInput("B", "Number", "3");
  math->addOutput("Result", "Number");
  math->setCodeTemplate("int {Result} = {A} + {B};\n{ExecOut}");

  // Print node consumes Value via data link
  Node *print = project.graph()->addNode("IO.Print", "Print", QPointF(200, 0));
  print->addInput("ExecIn", "Exec");
  print->addInput("Value", "Number", "");
  print->setCodeTemplate("std::cout << {Value};\n");

  // Exec: start -> math -> print
  project.graph()->addLink(start->id(), start->outputs()[0].id, math->id(),
                           math->inputs()[0].id);
  project.graph()->addLink(math->id(), math->outputs()[0].id, print->id(),
                           print->inputs()[0].id);
  // Data: math.Result -> print.Value
  project.graph()->addLink(math->id(), math->outputs()[1].id, print->id(),
                           print->inputs()[1].id);

  QString code = CodeGenerator::generate(&project);
  // print should reference the math node's Result variable (with prefix)
  EXPECT_TRUE(code.contains("n_"));
  EXPECT_TRUE(code.contains("Result"));
}

// ── Unlinked Input Error ────────────────────────────────────────────────────

TEST_F(CodeGenFixture, UnlinkedInputWithNoValueReportsError) {
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  Node *print = project.graph()->addNode("IO.Print", "Print", QPointF(100, 0));
  print->addInput("ExecIn", "Exec");
  print->addInput("Text", "String", ""); // empty value, no data link
  print->setCodeTemplate("print({Text});\n");

  project.graph()->addLink(start->id(), start->outputs()[0].id, print->id(),
                           print->inputs()[0].id);

  auto result = CodeGenerator::generateWithErrors(&project);
  EXPECT_FALSE(result.errorNodes.isEmpty());
  EXPECT_FALSE(result.errors.isEmpty());
  EXPECT_TRUE(result.errors[0].contains("unlinked"));
}

TEST_F(CodeGenFixture, UnlinkedInputWithValueNoError) {
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  Node *print = project.graph()->addNode("IO.Print", "Print", QPointF(100, 0));
  print->addInput("ExecIn", "Exec");
  print->addInput("Text", "String", "hello");
  print->setCodeTemplate("print({Text});\n");

  project.graph()->addLink(start->id(), start->outputs()[0].id, print->id(),
                           print->inputs()[0].id);

  auto result = CodeGenerator::generateWithErrors(&project);
  EXPECT_TRUE(result.errorNodes.isEmpty());
}

// ── Cycle Detection ─────────────────────────────────────────────────────────

TEST_F(CodeGenFixture, CycleDetectionInExecFlow) {
  Node *a = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  a->addOutput("Exec", "Exec");
  a->setCodeTemplate("// start\n{Exec}");

  Node *b = project.graph()->addNode("IO.Print", "Print", QPointF(100, 0));
  b->addInput("ExecIn", "Exec");
  b->addOutput("ExecOut", "Exec");
  b->setCodeTemplate("// print\n{ExecOut}");

  Node *c = project.graph()->addNode("IO.Print2", "Print2", QPointF(200, 0));
  c->addInput("ExecIn", "Exec");
  c->addOutput("ExecOut", "Exec");
  c->setCodeTemplate("// print2\n{ExecOut}");

  // a -> b -> c -> b (cycle)
  project.graph()->addLink(a->id(), a->outputs()[0].id, b->id(),
                           b->inputs()[0].id);
  project.graph()->addLink(b->id(), b->outputs()[0].id, c->id(),
                           c->inputs()[0].id);
  project.graph()->addLink(c->id(), c->outputs()[0].id, b->id(),
                           b->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  EXPECT_FALSE(code.contains("cycle detected"));
}

// ── Branch Indentation ──────────────────────────────────────────────────────

TEST_F(CodeGenFixture, TrueFalseBranchesAreIndented) {
  Node *ifNode =
      project.graph()->addNode("Control.If.Start", "If", QPointF(0, 0));
  ifNode->addInput("Condition", "Boolean", "true");
  ifNode->addOutput("True", "Exec");
  ifNode->addOutput("False", "Exec");
  ifNode->setCodeTemplate("if ({Condition}) {\n{True}\n} else {\n{False}\n}\n");

  Node *trueNode =
      project.graph()->addNode("IO.PrintT", "PrintTrue", QPointF(200, 0));
  trueNode->addInput("ExecIn", "Exec");
  trueNode->addInput("Text", "String", "yes");
  trueNode->setCodeTemplate("print({Text});\n");

  Node *falseNode =
      project.graph()->addNode("IO.PrintF", "PrintFalse", QPointF(200, 100));
  falseNode->addInput("ExecIn", "Exec");
  falseNode->addInput("Text", "String", "no");
  falseNode->setCodeTemplate("print({Text});\n");

  project.graph()->addLink(ifNode->id(), ifNode->outputs()[0].id,
                           trueNode->id(), trueNode->inputs()[0].id);
  project.graph()->addLink(ifNode->id(), ifNode->outputs()[1].id,
                           falseNode->id(), falseNode->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("if (true)"));
  EXPECT_TRUE(code.contains("    print(\"yes\")"));
  EXPECT_TRUE(code.contains("    print(\"no\")"));
}

TEST_F(CodeGenFixture, LoopBodyIsIndented) {
  Node *whileNode =
      project.graph()->addNode("Control.While.Start", "While", QPointF(0, 0));
  whileNode->addInput("Condition", "Boolean", "true");
  whileNode->addOutput("Loop", "Exec");
  whileNode->setCodeTemplate("while ({Condition}) {\n{Loop}\n}\n");

  Node *body =
      project.graph()->addNode("IO.BodyPrint", "BodyPrint", QPointF(200, 0));
  body->addInput("ExecIn", "Exec");
  body->addInput("Text", "String", "looping");
  body->setCodeTemplate("print({Text});\n");

  project.graph()->addLink(whileNode->id(), whileNode->outputs()[0].id,
                           body->id(), body->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("while (true)"));
  EXPECT_TRUE(code.contains("    print(\"looping\")"));
}

// ── VALUE template replacement ──────────────────────────────────────────────

TEST_F(CodeGenFixture, ValueTemplateReplacement) {
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  Node *n = project.graph()->addNode("Data.Var", "MyVar", QPointF(100, 0));
  n->addInput("ExecIn", "Exec");
  n->setHasValue(true);
  n->setValue("myVariable");
  n->addOutput("Value", "Number");
  n->setCodeTemplate("auto {Value} = {VALUE};\n");

  project.graph()->addLink(start->id(), start->outputs()[0].id, n->id(),
                           n->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("myVariable"));
}

// ── Multiple disconnected start nodes ───────────────────────────────────────

TEST_F(CodeGenFixture, MultipleStartNodesGenerateSeparateCode) {
  Node *s1 = project.graph()->addNode("C++.Start", "Start1", QPointF(0, 0));
  s1->addOutput("Exec", "Exec");
  s1->setCodeTemplate("// block1\n{Exec}");

  Node *s2 = project.graph()->addNode("C++.Start", "Start2", QPointF(0, 100));
  s2->addOutput("Exec", "Exec");
  s2->setCodeTemplate("// block2\n{Exec}");

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("block1"));
  EXPECT_TRUE(code.contains("block2"));
}

// ── generateSingleNode (standalone, no exec flow needed) ────────────────────

TEST_F(CodeGenFixture, GenerateSingleNodeBasic) {
  Node node("Math.Add", "Add");
  node.addInput("A", "Number", "5");
  node.addInput("B", "Number", "3");
  node.addOutput("Result", "Number");
  node.setCodeTemplate("int {Result} = {A} + {B};");

  QString code = CodeGenerator::generateSingleNode(&node);
  EXPECT_EQ(code, "int Result = 5 + 3;");
}

TEST_F(CodeGenFixture, GenerateSingleNodeEmptyInputUsesPlaceholder) {
  Node node("Math.Add", "Add");
  node.addInput("A", "Number", "");
  node.addInput("B", "Number", "10");
  node.addOutput("Result", "Number");
  node.setCodeTemplate("int {Result} = {A} + {B};");

  QString code = CodeGenerator::generateSingleNode(&node);
  EXPECT_EQ(code, "int Result = <A> + 10;");
}

TEST_F(CodeGenFixture, GenerateSingleNodeExecPortReplacement) {
  Node node("IO.Print", "Print");
  node.addInput("ExecIn", "Exec");
  node.addOutput("ExecOut", "Exec");
  node.addInput("Text", "String", "hello");
  node.setCodeTemplate("print({Text});\n{ExecOut}");

  QString code = CodeGenerator::generateSingleNode(&node);
  EXPECT_TRUE(code.contains("print(hello);"));
  EXPECT_TRUE(code.contains("..."));
}

TEST_F(CodeGenFixture, GenerateSingleNodeWithValue) {
  Node node("Data.Const", "Constant");
  node.setHasValue(true);
  node.setValue("42");
  node.addOutput("Value", "Number");
  node.setCodeTemplate("auto {Value} = {VALUE};");

  QString code = CodeGenerator::generateSingleNode(&node);
  EXPECT_EQ(code, "auto Value = 42;");
}

TEST_F(CodeGenFixture, GenerateSingleNodeNullReturnsEmpty) {
  QString code = CodeGenerator::generateSingleNode(nullptr);
  EXPECT_EQ(code, "");
}

// ── Dependencies via loaded definitions ─────────────────────────────────────

TEST_F(CodeGenFixture, DependencyIncludesCpp) {
  QTemporaryDir tempDir;
  QString defPath = tempDir.path() + "/defs.node";
  QFile f(defPath);
  f.open(QIODevice::WriteOnly);
  f.write(R"({
    "nodes": [{
      "type": "IO.PrintStd",
      "name": "PrintStd",
      "inputs": [{"name": "ExecIn", "type": "Exec"}, {"name": "Text", "type": "String", "value": "hi"}],
      "outputs": [],
      "code": "std::cout << {Text};\n",
      "language": "C++",
      "requires": ["<iostream>"]
    }]
  })");
  f.close();

  project.setLanguage("C++");
  ASSERT_TRUE(project.loadNodeDefinitions(defPath));

  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  Node *print =
      project.graph()->addNode("IO.PrintStd", "PrintStd", QPointF(100, 0));
  print->addInput("ExecIn", "Exec");
  print->addInput("Text", "String", "hi");
  print->setCodeTemplate("std::cout << {Text};\n");

  project.graph()->addLink(start->id(), start->outputs()[0].id, print->id(),
                           print->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("#include <iostream>"));
}

TEST_F(CodeGenFixture, DependencyImportsPython) {
  QTemporaryDir tempDir;
  QString defPath = tempDir.path() + "/defs.node";
  QFile f(defPath);
  f.open(QIODevice::WriteOnly);
  f.write(R"({
    "nodes": [{
      "type": "Net.Fetch",
      "name": "Fetch",
      "inputs": [{"name": "ExecIn", "type": "Exec"}, {"name": "URL", "type": "String", "value": "http://example.com"}],
      "outputs": [],
      "code": "requests.get({URL})\n",
      "language": "Python",
      "requires": ["requests"]
    }]
  })");
  f.close();

  project.setLanguage("Python");
  ASSERT_TRUE(project.loadNodeDefinitions(defPath));

  Node *start =
      project.graph()->addNode("Python.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  Node *fetch = project.graph()->addNode("Net.Fetch", "Fetch", QPointF(100, 0));
  fetch->addInput("ExecIn", "Exec");
  fetch->addInput("URL", "String", "http://example.com");
  fetch->setCodeTemplate("requests.get({URL})\n");

  project.graph()->addLink(start->id(), start->outputs()[0].id, fetch->id(),
                           fetch->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("import requests"));
}

TEST_F(CodeGenFixture, DependencyRequiresJavaScript) {
  QTemporaryDir tempDir;
  QString defPath = tempDir.path() + "/defs.node";
  QFile f(defPath);
  f.open(QIODevice::WriteOnly);
  f.write(R"({
    "nodes": [{
      "type": "Net.Http",
      "name": "Http",
      "inputs": [{"name": "ExecIn", "type": "Exec"}],
      "outputs": [],
      "code": "http.get('/');\n",
      "language": "JavaScript",
      "requires": ["http"]
    }]
  })");
  f.close();

  project.setLanguage("JavaScript");
  ASSERT_TRUE(project.loadNodeDefinitions(defPath));

  Node *start = project.graph()->addNode("JS.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("{Exec}");

  Node *http = project.graph()->addNode("Net.Http", "Http", QPointF(100, 0));
  http->addInput("ExecIn", "Exec");
  http->setCodeTemplate("http.get('/');\n");

  project.graph()->addLink(start->id(), start->outputs()[0].id, http->id(),
                           http->inputs()[0].id);

  QString code = CodeGenerator::generate(&project);
  EXPECT_TRUE(code.contains("const http = require('http');"));
}

TEST_F(CodeGenFixture, SwitchingProjectLanguageChangesOutput) {
  // 1. Start with C++
  project.setLanguage("C++");
  Node *start = project.graph()->addNode("C++.Start", "Start", QPointF(0, 0));
  start->addOutput("Exec", "Exec");
  start->setCodeTemplate("int main() { {Exec} }");

  QString codeCpp = CodeGenerator::generate(&project);
  EXPECT_TRUE(codeCpp.contains("int main()"));

  // 2. Switch to Python
  project.setLanguage("Python");
  QString codePy = CodeGenerator::generate(&project);

  // Since we didn't clear the graph, the C++ node is still there.
  // The generator should still find it and generate its C++ template,
  // even if the project is "Python". This tests that nodes are independent.
  EXPECT_TRUE(codePy.contains("int main()"));

  // 3. Clear and add Python nodes specifically
  project.graph()->clear();
  Node *pyStart =
      project.graph()->addNode("Python.Start", "Start", QPointF(0, 0));
  pyStart->addOutput("Exec", "Exec");
  pyStart->setCodeTemplate("def main():\n    {Exec}");

  QString codePyReal = CodeGenerator::generate(&project);
  EXPECT_TRUE(codePyReal.contains("def main():"));
  EXPECT_FALSE(codePyReal.contains("int main()"));
}
