#include "CodeGenerator.h"
#include "Project.h"
#include <QSet>
#include <functional>

QString CodeGenerator::generate(Project *project) {
  auto result = generateWithErrors(project);
  return result.code;
}

GenerationResult CodeGenerator::generateWithErrors(Project *project) {
  GenerationResult result;
  if (project->graph()->nodes().isEmpty()) {
    result.code = "// Pipeline empty.\n";
    return result;
  }

  QMap<QUuid, QString> nodePrefixes;
  int nodeIdx = 0;
  QSet<QString> dependencies;
  auto defs = project->nodeDefinitions();

  for (auto *n : project->graph()->nodes()) {
    nodePrefixes[n->id()] = "n_" + QString::number(nodeIdx++) + "_";
    if (defs.contains(n->type())) {
      for (const auto &req : defs[n->type()].requires) {
        dependencies.insert(req);
      }
    }
  }

  QString finalCode = "";
  if (!dependencies.isEmpty()) {
    finalCode += "// Dependencies\n";
    for (const auto &dep : dependencies) {
      if (project->language() == "C++") {
        if (dep.contains("<"))
          finalCode += "#include " + dep + "\n";
        else
          finalCode += "#include \"" + dep + "\"\n";
      } else if (project->language() == "Python") {
        finalCode += "import " + dep + "\n";
      } else if (project->language() == "JavaScript") {
        finalCode += "const " + dep + " = require('" + dep + "');\n";
      }
    }
    finalCode += "\n";
  }

  finalCode += "// Generated by NodeCode Studio\n\n";

  QSet<QUuid> generatedNodes;

  std::function<QString(Node *)> generateNodeCode = [&](Node *node) -> QString {
    if (!node)
      return "";
    if (generatedNodes.contains(node->id()))
      return "/* cycle detected */\n";
    generatedNodes.insert(node->id());

    QString tpl = node->codeTemplate();
    tpl.replace("{VALUE}", node->value());

    for (const auto &out : node->outputs()) {
      if (out.dataType != "Exec") {
        tpl.replace("{" + out.name + "}", nodePrefixes[node->id()] + out.name);
      }
    }

    for (const auto &in : node->inputs()) {
      if (in.dataType == "Exec")
        continue;

      QString connectedVar = "/* unlinked */";
      for (const auto *link : project->graph()->links()) {
        if (link->targetNodeId == node->id() && link->targetPortId == in.id) {
          Node *src = project->graph()->getNode(link->sourceNodeId);
          if (src) {
            QString outName;
            for (const auto &out : src->outputs()) {
              if (out.id == link->sourcePortId) {
                outName = out.name;
                break;
              }
            }
            if (!outName.isEmpty()) {
              connectedVar = nodePrefixes[src->id()] + outName;
            }
          }
          break;
        }
      }

      if (connectedVar == "/* unlinked */") {
        if (!in.value.isEmpty()) {
          bool isNum;
          in.value.toDouble(&isNum);
          bool isBool = (in.value == "true" || in.value == "false" ||
                         in.value == "True" || in.value == "False");
          if (in.dataType == "String" ||
              (in.dataType == "Any" && !isNum && !isBool)) {
            connectedVar = "\"" + in.value + "\"";
          } else {
            connectedVar = in.value;
          }
        } else {
          result.errorNodes.append(node->id());
          result.errors.append("Node '" + node->name() + "' has unlinked input '" + in.name + "'");
        }
      }
      tpl.replace("{" + in.name + "}", connectedVar);
    }

    for (const auto &out : node->outputs()) {
      if (out.dataType == "Exec") {
        QString flowCode = "";
        for (const auto *link : project->graph()->links()) {
          if (link->sourceNodeId == node->id() &&
              link->sourcePortId == out.id) {
            Node *next = project->graph()->getNode(link->targetNodeId);
            if (next) {
              flowCode = generateNodeCode(next);
            }
            break;
          }
        }
        if (out.name == "True" || out.name == "False" || out.name == "Loop" ||
            out.name == "Callback" || out.name == "Body" || out.name == "Catch") {
          if (!flowCode.isEmpty()) {
            QStringList lines = flowCode.split("\n");
            for (int i = 0; i < lines.size(); ++i) {
              if (!lines[i].trimmed().isEmpty())
                lines[i] = "    " + lines[i];
            }
            flowCode = lines.join("\n");
          }
        }
        tpl.replace("{" + out.name + "}", flowCode);
      }
    }

    return tpl;
  };

  for (auto *node : project->graph()->nodes()) {
    bool hasExecIn = false;
    for (const auto &in : node->inputs()) {
      if (in.dataType == "Exec") {
        for (const auto *link : project->graph()->links()) {
          if (link->targetNodeId == node->id() && link->targetPortId == in.id) {
            hasExecIn = true;
            break;
          }
        }
      }
      if (hasExecIn)
        break;
    }

    bool hasExecOut = false;
    for (const auto &out : node->outputs())
      if (out.dataType == "Exec")
        hasExecOut = true;

    if (node->type().endsWith(".Start") || (!hasExecIn && hasExecOut)) {
      generatedNodes.clear();
      finalCode += generateNodeCode(node) + "\n";
    }
  }

  result.code = finalCode;
  return result;
}

QString CodeGenerator::generateSingleNode(Node *node) {
  if (!node) return "";
  QString tpl = node->codeTemplate();
  tpl.replace("{VALUE}", node->value());
  for (const auto &in : node->inputs()) {
    if (in.dataType != "Exec")
      tpl.replace("{" + in.name + "}", in.value.isEmpty() ? ("<" + in.name + ">") : in.value);
  }
  for (const auto &out : node->outputs()) {
    if (out.dataType == "Exec")
      tpl.replace("{" + out.name + "}", "...");
    else
      tpl.replace("{" + out.name + "}", out.name);
  }
  return tpl;
}
