#include "CodeGenerator.h"
#include "Project.h"
#include <QSet>
#include <functional>

namespace {
// Helper to determine if a node is strictly for data (no execution flow)
bool isPureDataNode(Node *node) {
  if (!node)
    return false;
  for (const auto &pin : node->inputs()) {
    if (pin.dataType == "Exec")
      return false;
  }
  for (const auto &pin : node->outputs()) {
    if (pin.dataType == "Exec")
      return false;
  }
  return true;
}
} // namespace

QString CodeGenerator::generate(Project *project) {
  auto result = generateWithErrors(project);
  return result.code;
}

GenerationResult CodeGenerator::generateWithErrors(Project *project) {
  GenerationResult result;
  if (project->graph()->nodes().isEmpty()) {
    result.code = "// Pipeline empty.\n";
    return result;
  }

  QMap<QUuid, QString> nodePrefixes;
  int nodeIdx = 0;
  QSet<QString> dependencies;
  auto defs = project->nodeDefinitions();

  for (auto *n : project->graph()->nodes()) {
    nodePrefixes[n->id()] = "n_" + QString::number(nodeIdx++) + "_";
    if (defs.contains(n->type())) {
      for (const auto &req : defs[n->type()].requires) {
        dependencies.insert(req);
      }
    }
  }

  QString finalCode = "";
  if (!dependencies.isEmpty()) {
    finalCode += "// Dependencies\n";
    for (const auto &dep : dependencies) {
      if (project->language() == "C++") {
        if (dep.contains("<"))
          finalCode += "#include " + dep + "\n";
        else
          finalCode += "#include \"" + dep + "\"\n";
      } else if (project->language() == "Python") {
        finalCode += "import " + dep + "\n";
      } else if (project->language() == "JavaScript") {
        finalCode += "const " + dep + " = require('" + dep + "');\n";
      }
    }
    finalCode += "\n";
  }

  finalCode += "// Generated by NodeCode Studio\n\n";

  QSet<QUuid> generatedNodes;

  std::function<QString(Node *)> generateNodeCode = [&](Node *node) -> QString {
    if (!node)
      return "";

    // Skip if already generated to prevent dupes in the AST cache
    if (generatedNodes.contains(node->id()))
      return "";

    generatedNodes.insert(node->id());

    QString dataDependenciesCode = "";
    QString tpl = node->codeTemplate();
    tpl.replace("{VALUE}", node->value());

    // Pre-replace outputs
    for (const auto &out : node->outputs()) {
      if (out.dataType != "Exec") {
        tpl.replace("{" + out.name + "}", nodePrefixes[node->id()] + out.name);
      }
    }

    // Process inputs and recursively pull pure data dependencies
    for (const auto &in : node->inputs()) {
      if (in.dataType == "Exec")
        continue;

      QString connectedVar = "/* unlinked */";
      for (const auto *link : project->graph()->links()) {
        if (link->targetNodeId == node->id() && link->targetPortId == in.id) {
          Node *src = project->graph()->getNode(link->sourceNodeId);
          if (src) {

            // If the source is a pure data node, eagerly evaluate it BEFORE
            // this node
            if (isPureDataNode(src) && !generatedNodes.contains(src->id())) {
              QString srcCode = generateNodeCode(src);
              if (!srcCode.isEmpty()) {
                if (!dataDependenciesCode.isEmpty() &&
                    !dataDependenciesCode.endsWith("\n"))
                  dataDependenciesCode += "\n";
                dataDependenciesCode += srcCode;
              }
            }

            QString outName;
            for (const auto &out : src->outputs()) {
              if (out.id == link->sourcePortId) {
                outName = out.name;
                break;
              }
            }
            if (!outName.isEmpty()) {
              connectedVar = nodePrefixes[src->id()] + outName;
            }
          }
          break;
        }
      }

      if (connectedVar == "/* unlinked */") {
        if (!in.value.isEmpty()) {
          bool isNum;
          in.value.toDouble(&isNum);
          bool isBool = (in.value == "true" || in.value == "false" ||
                         in.value == "True" || in.value == "False");
          if (in.dataType == "String" ||
              (in.dataType == "Any" && !isNum && !isBool)) {
            connectedVar = "\"" + in.value + "\"";
          } else {
            connectedVar = in.value;
          }
        } else {
          result.errorNodes.append(node->id());
          result.errors.append("Node '" + node->name() +
                               "' has unlinked input '" + in.name + "'");
        }
      }
      tpl.replace("{" + in.name + "}", connectedVar);
    }

    // Process Exec outputs for flow logic
    for (const auto &out : node->outputs()) {
      if (out.dataType == "Exec") {
        QString flowCode = "";
        for (const auto *link : project->graph()->links()) {
          if (link->sourceNodeId == node->id() &&
              link->sourcePortId == out.id) {
            Node *next = project->graph()->getNode(link->targetNodeId);
            if (next) {
              flowCode = generateNodeCode(next);
            }
            break;
          }
        }
        if (out.name == "True" || out.name == "False" || out.name == "Loop" ||
            out.name == "Callback" || out.name == "Body" ||
            out.name == "Catch") {
          if (!flowCode.isEmpty()) {
            QStringList lines = flowCode.split("\n");
            for (int i = 0; i < lines.size(); ++i) {
              if (!lines[i].trimmed().isEmpty())
                lines[i] = "    " + lines[i];
            }
            flowCode = lines.join("\n");
          }
        }
        tpl.replace("{" + out.name + "}", flowCode);
      }
    }

    QString finalNodeCode = dataDependenciesCode;
    if (!finalNodeCode.isEmpty() && !finalNodeCode.endsWith("\n")) {
      finalNodeCode += "\n";
    }
    finalNodeCode += tpl;
    return finalNodeCode;
  };

  for (auto *node : project->graph()->nodes()) {
    bool hasExecIn = false;
    for (const auto &in : node->inputs()) {
      if (in.dataType == "Exec") {
        for (const auto *link : project->graph()->links()) {
          if (link->targetNodeId == node->id() && link->targetPortId == in.id) {
            hasExecIn = true;
            break;
          }
        }
      }
    }

    bool hasExecOut = false;
    for (const auto &out : node->outputs())
      if (out.dataType == "Exec")
        hasExecOut = true;

    // Only start execution chains from root flow nodes
    if (node->type().endsWith(".Start") || (!hasExecIn && hasExecOut)) {
      QString block = generateNodeCode(node);
      if (!block.isEmpty()) {
        finalCode += block + "\n";
      }
    }
  }

  result.code = finalCode;
  return result;
}

QString CodeGenerator::generateSingleNode(Node *node) {
  if (!node)
    return "";
  QString tpl = node->codeTemplate();
  tpl.replace("{VALUE}", node->value());
  for (const auto &in : node->inputs()) {
    if (in.dataType != "Exec")
      tpl.replace("{" + in.name + "}",
                  in.value.isEmpty() ? ("<" + in.name + ">") : in.value);
  }
  for (const auto &out : node->outputs()) {
    if (out.dataType == "Exec")
      tpl.replace("{" + out.name + "}", "...");
    else
      tpl.replace("{" + out.name + "}", out.name);
  }
  return tpl;
}